import { UserButton } from "@clerk/nextjs";
import { auth, currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { KTutor } from "@/app/components/k-tutor";
import { LessonStyleFix } from "@/app/components/lesson-style-fix";
import { KSceneStyleFix } from "@/app/components/k-scene-style-fix";
import { kScenes } from "@/lib/k-scenes";

export default async function KSceneHub(){const{userId}=await auth();if(!userId)redirect("/sign-in");const user=await currentUser();const name=user?.firstName||user?.username||"Ученик";return <><LessonStyleFix/><KSceneStyleFix/><nav className="learn-nav"><a className="learn-logo" href="/studio"><span>ㅋ</span>K‑Lab</a><div><a href="/studio">МОЙ РИТМ</a><a href="/learn/lesson-01-introduction">УРОКИ</a><a href="https://k-lab-two.vercel.app/speaking.html">SPEAKING</a><a href="/vocabulary">WORD DECK</a><a className="active" href="/k-scene">K‑SCENE</a></div><section><b>{name}</b><UserButton appearance={{elements:{avatarBox:"learn-avatar"}}}/></section></nav><main className="scene-hub"><header className="scene-hero"><div><span>K‑SCENE · SHADOWING LAB</span><h1>Говори<br/>как в сцене.</h1><p>Здесь фразы из твоих уроков звучат в контексте: послушай реплику, повтори за персонажем и отправь её в Speaking Lab.</p></div><aside><b>4 ЖИВЫЕ СЦЕНЫ</b><p>У каждой — своя локация, диалог и персонажи. Джун появляется в сцене про распорядок дня.</p></aside></header><section className="scene-grid">{kScenes.map(scene=><a className="scene-card" href={`/k-scene/${scene.slug}`} key={scene.id}><figure><img src={scene.cover} alt={scene.location}/><img src={scene.cast} alt={`Персонажи: ${scene.title}`}/></figure><div><small>{scene.lesson.toUpperCase()} · {scene.location.toUpperCase()}</small><h2>{scene.title}</h2><p>{scene.lines.length} реплики · слушай, повторяй, сохраняй прохождение →</p></div></a>)}</section></main><KTutor lessonContext="K-Scene hub. Помоги пользователю понять реплику перед началом сцены."/></>}
